version: "3.8"
services:
  # user mgmt microservice
  user_mgmt:
    container_name: go-blogging-user-mgmt
    build:
      context: ./user-mgmt-svc/local
    command: make start
    environment:
      ENV: development
      POSTGRES_URL: postgres://postgres:root@db:5432/user_mgmt?sslmode=disable
      JWT_SECRET: FN3H35wZS2jpkbBZ
    depends_on:
      - db
    volumes:
      - ./user-mgmt-svc:/app
    ports:
      - 8080:8080

  # article microservice
  article:
    container_name: go-blogging-article
    build:
      context: ./article-svc/local
    command: make start
    environment:
      ENV: development
      POSTGRES_URL: postgres://postgres:root@db:5432/article_svc?sslmode=disable
    depends_on:
      - db
    volumes:
      - ./article-svc:/app
    ports:
      - 8081:8080
      - 2345:2345

  # db
  db:
    image: postgres:14.5-alpine
    container_name: go-blogging-db
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "user_mgmt"
    ports:
      - 5432:5432
